services:
  - type: web
    name: video-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT server:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
